---
name: LAB Submission Form
about: Use this template to submit your lab assignment.
title: '[LAB] Week X_yourname'

---
## Week

Please select the week of lecture for which you are submitting the assignment:

<select name="Week" required>
<option value="" selected disabled>Please select</option>
<option value="1">Week 1</option>
</select>

## Code Submission

Please submit your code below.

<textarea name="Code" placeholder="Please paste your code here." required></textarea>

<textarea name="Description" placeholder="Please briefly describe what your code does, including any libraries or frameworks used." required></textarea>

**Output Description (Optional)**

If your code generates output, please describe it here.

<textarea name="Output Description" placeholder="(Optional) Please describe the output that your code generated."></textarea>
