name: LAB Submission Form
description: Use this template to submit your lab assignment.
title: "[LAB] Week X_yourname"
labels: ["lab"]
body:
  - type: dropdown
    id: week
    attributes:
      label: Week
      description: "Please select the week of lecture for which you are submitting the assignment:"
      options:
        - Week 1
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Source Code
      description: Please paste your code here.
      render: python

  - type: textarea
    id: desc
    attributes:
      label: Description
      description: Please briefly describe what your code does.

  - type: textarea
    id: output
    attributes:
      label: Output (Optional)
      description: (Optional) Please describe the output that your code generated.
